# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: nextcloud server add-on
version: "0.0.1"
slug: nextcloud
description: nextcloud server add-on
url: "https://github.com/Eek1986/home-assistent-addons/nextcloud"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
map:
  - share:rw
ports:
  80/tcp: 8080
options:
  message: "Hello world..."
  MYSQL_PASSWORD: "password"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "unextcloud:
  MYSQL_HOST: "addon_core_mariadb"
schema:
  message: "str?"
  MYSQL_PASSWORD: "str?"
  MYSQL_DATABASE: "str?"
  MYSQL_USER: "str?:
  MYSQL_HOST: "str?"

#image: "ghcr.io/Eek1986/{arch}-addon-nextcloud"
