# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: nextcloud server add-on
version: "0.0.1"
slug: nextcloud
description: nextcloud server add-on
url: "https://github.com/Eek1986/home-assistent-addons/nextcloud"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/Eek1986/{arch}-addon-nextcloud"
